name: justin_rl_api
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - click=8.1.7
  - colorama=0.4.6
  - greenlet=3.1.1
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - krb5=1.20.1
  - libffi=3.4.4
  - libpq=17.2
  - markupsafe=2.1.3
  - openssl=3.0.15
  - pip=24.2
  - psycopg2=2.9.9
  - python=3.11.11
  - python-dotenv=1.1.0
  - setuptools=75.1.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - alembic==1.14.0
      - black==24.10.0
      - blinker==1.9.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - flake8==7.1.1
      - flask==3.1.0
      - flask-migrate==4.0.7
      - flask-sqlalchemy==3.1.1
      - idna==3.10
      - iniconfig==2.0.0
      - mako==1.3.8
      - mccabe==0.7.0
      - mypy-extensions==1.0.0
      - numpy==2.2.1
      - packaging==24.2
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
      - pytest==8.3.4
      - pytest-flask==1.3.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - responses==0.25.3
      - urllib3==2.3.0
      - werkzeug==3.1.3
